specifyFunction2 (listFilter <Nat>)
  [ (isEven, []<Nat>, []<Nat>)
  -- , (isEven, [0]<Nat>, [0]<Nat>)
  -- , (isEven, [1]<Nat>, []<Nat>)
  -- , (isEven, [2]<Nat>, [2]<Nat>)
  , (isEven, [0, 0]<Nat>, [0, 0]<Nat>)
  -- , (isEven, [0, 1]<Nat>, [0]<Nat>)
  , (isEven, [1, 0, 1]<Nat>, [0]<Nat>)
  -- , (isNonzero, []<Nat>, []<Nat>)
  -- , (isNonzero, [0]<Nat>, []<Nat>)
  ]
