specifyFunction3 (listFold <Nat, Nat>)
  [ (sum, 0, []<Nat>, 0)
  -- , (sum, 0, [1]<Nat>, 1)
  , (sum, 0, [2, 1]<Nat>, 3)
  -- , (sum, 0, [3, 2, 1]<Nat>, 6)
  -- , (sum, 1, []<Nat>, 1)
  -- , (countOdd, 0, []<Nat>, 0)
  -- , (countOdd, 0, [1]<Nat>, 1)
  -- , (countOdd, 0, [2, 1]<Nat>, 1)
  -- , (countOdd, 0, [3, 2, 1]<Nat>, 2)
  ]
