#!/bin/bash

mkdir -p data/exp-3b
mkdir -p data-backup/exp-3b
mv data/exp-3b/*.csv data-backup/exp-3b 2> /dev/null

run() {
  echo -n "(3b) Running $1... "
  ./fuzz base-case-sketch $1 > data/exp-3b/$1.csv
  if [ $? -eq 0 ]; then
    echo "completed."
  else
    echo ""
  fi
}

# run bool_band
# run bool_bor
# run bool_impl
# run bool_neg
# run bool_xor

run list_append
# run list_compress
run list_concat
run list_drop
run list_even_parity
# run list_filter
# run list_fold
# run list_hd
# run list_inc
run list_last
run list_length
# run list_map
run list_nth
run list_pairwise_swap
run list_rev_append
run list_rev_fold
# run list_rev_snoc
run list_rev_tailcall
run list_snoc
run list_sort_sorted_insert
run list_sorted_insert
run list_stutter

# run list_sum
run list_take
# run list_tl
run nat_iseven

run nat_max
run nat_pred
run nat_add

# run tree_binsert
run tree_collect_leaves
run tree_count_nodes
run tree_inorder
# run tree_map
# run tree_nodes_at_level
# run tree_postorder
run tree_preorder

# Benchmarks requiring longer timeout
run list_sorted_insert
run list_pairwise_swap
run tree_count_leaves
