#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cat \
  $DIR/suites/suite-$1/$2.elm \
  $DIR/suites/suite-$1/examples/$2.elm \
  > $DIR/forge_temp_file

$DIR/smyth forge $DIR/forge_temp_file

rm $DIR/forge_temp_file
