#!/bin/bash

if [[ $# -ne 0 ]]; then
  echo "usage:" $0
  exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

mkdir -p specifications/mono
mkdir -p specifications-backup/mono
mv specifications/mono/*.elm specifications-backup/mono 2> /dev/null

run() {
  $DIR/smyth generate-spec $1 > specifications/mono/$1.elm
}

run bool_band
run bool_bor
run bool_impl
run bool_neg
run bool_xor
run list_append
run list_compress
run list_concat
run list_drop
run list_even_parity
run list_filter
run list_fold
run list_hd
run list_inc
run list_last
run list_length
run list_map
run list_nth
run list_pairwise_swap
run list_rev_append
run list_rev_fold
run list_rev_snoc
run list_rev_tailcall
run list_snoc
run list_sort_sorted_insert
run list_sorted_insert
run list_stutter
run list_sum
run list_take
run list_tl
run nat_add
run nat_iseven
run nat_max
run nat_pred
run tree_binsert
run tree_collect_leaves
run tree_count_leaves
run tree_count_nodes
run tree_inorder
run tree_map
run tree_nodes_at_level
run tree_postorder
run tree_preorder
