#!/bin/bash

if [[ $# -ne 1 ]]; then
  echo "usage:" $0 "<suite-name>"
  exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

$DIR/smyth suite-test \
  $DIR/suites/specifications \
  $DIR/suites/suite-$1
