#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

$DIR/smyth test \
  $DIR/suites/specifications/$2.elm \
  $DIR/suites/suite-$1/$2.elm \
  $DIR/suites/suite-$1/examples/$2.elm
