specifyFunction evenParity
  [ ([], T)
  , ([T, F], F)
  , ([T, F, F, F], F)
  , ([F], T)
  , ([T], F)
  , ([F, T, F, F], F)
  , ([F, F], T)
  , ([F, F, T], F)
  , ([T, T, F], T)
  , ([F, F, T, F], F)
  , ([T, T, F, T], F)
  , ([F, F, F, F], T)
  , ([T, T], T)
  , ([T, F, F], F)
  , ([F, T, T], T)
  ]
