specifyFunction concat
  [ (LNil, [])
  , (LCons ([0], LCons ([], LCons ([0, 2], LNil))), [0, 0, 2])
  , (LCons ([0], LNil), [0])
  , (LCons ([1], LCons ([3, 3], LNil)), [1, 3, 3])
  , (LCons ([2], LCons ([], LCons ([], LCons ([2, 1], LNil)))), [2, 2, 1])
  , (LCons ([1], LCons ([1, 1], LNil)), [1, 1, 1])
  , (LCons ([0], LCons ([1, 3], LCons ([], LNil))), [0, 1, 3])
  , (LCons ([], LCons ([], LNil)), [])
  , (LCons ([2], LCons ([3], LNil)), [2, 3])
  , (LCons ([3], LNil), [3])
  , (LCons ([], LNil), [])
  , (LCons ([3, 3], LCons ([], LCons ([0], LCons ([], LNil)))), [3, 3, 0])
  , (LCons ([0], LCons ([0], LNil)), [0, 0])
  , (LCons ([3], LCons ([], LCons ([3], LCons ([], LNil)))), [3, 3])
  , (LCons ([2], LCons ([2], LCons ([2], LCons ([1], LNil)))), [2, 2, 2, 1])
  , (LCons ([1, 1], LCons ([], LCons ([1, 1], LNil))), [1, 1, 1, 1])
  , (LCons ([2, 3], LCons ([3, 1], LNil)), [2, 3, 3, 1])
  , (LCons ([0], LCons ([], LNil)), [0])
  , (LCons ([3], LCons ([0, 1], LCons ([], LNil))), [3, 0, 1])
  , (LCons ([0, 2], LNil), [0, 2])
  ]
