specifyFunction treeCountLeaves
  [ (Leaf, 1)
  , (Node (Leaf, F, Node (Node (Leaf, F, Leaf), F, Node (Node (Leaf, T, Leaf), F, Node (Leaf, T, Leaf)))), 7)
  , (Node (Leaf, F, Node (Leaf, T, Node (Node (Node (Leaf, F, Leaf), F, Leaf), T, Leaf))), 6)
  , (Node (Node (Leaf, T, Node (Leaf, T, Leaf)), T, Node (Node (Leaf, T, Leaf), F, Leaf)), 6)
  , (Node (Node (Leaf, T, Node (Node (Leaf, F, Node (Node (Leaf, F, Leaf), F, Leaf)), T, Leaf)), F, Leaf), 7)
  , (Node (Node (Node (Leaf, F, Leaf), F, Leaf), F, Node (Leaf, T, Node (Node (Leaf, F, Leaf), F, Leaf))), 7)
  , (Node (Node (Leaf, F, Node (Node (Node (Leaf, F, Leaf), F, Node (Leaf, T, Leaf)), T, Leaf)), F, Leaf), 7)
  , (Node (Node (Leaf, T, Node (Node (Leaf, F, Node (Leaf, T, Leaf)), F, Leaf)), F, Leaf), 6)
  , (Node (Leaf, T, Node (Node (Leaf, F, Node (Leaf, F, Leaf)), T, Node (Node (Leaf, T, Leaf), T, Leaf))), 7)
  , (Node (Leaf, T, Node (Node (Leaf, F, Node (Node (Leaf, T, Leaf), T, Node (Leaf, F, Leaf))), F, Leaf)), 7)
  , (Node (Leaf, F, Node (Node (Leaf, T, Node (Node (Leaf, T, Leaf), F, Leaf)), F, Leaf)), 6)
  , (Node (Node (Node (Leaf, F, Node (Leaf, T, Node (Leaf, T, Leaf))), T, Leaf), T, Node (Leaf, F, Leaf)), 7)
  , (Node (Node (Node (Leaf, T, Leaf), T, Leaf), T, Node (Node (Leaf, T, Node (Leaf, T, Leaf)), T, Leaf)), 7)
  , (Node (Leaf, F, Node (Node (Node (Leaf, F, Leaf), F, Node (Leaf, T, Node (Leaf, F, Leaf))), T, Leaf)), 7)
  , (Node (Node (Node (Leaf, F, Leaf), T, Leaf), T, Node (Node (Node (Leaf, T, Leaf), T, Leaf), T, Leaf)), 7)
  ]
