specifyFunction treeCountNodes
  [ (Leaf, 0)
  , (Node (Node (Leaf, 1, Leaf), 0, Node (Leaf, 2, Node (Leaf, 3, Leaf))), 4)
  , (Node (Leaf, 3, Node (Leaf, 2, Node (Leaf, 1, Node (Leaf, 0, Leaf)))), 4)
  , (Node (Leaf, 1, Node (Node (Node (Leaf, 1, Leaf), 1, Leaf), 3, Leaf)), 4)
  , (Node (Node (Leaf, 0, Node (Leaf, 0, Leaf)), 2, Node (Leaf, 2, Leaf)), 4)
  , (Node (Node (Leaf, 0, Leaf), 2, Leaf), 2)
  , (Node (Node (Leaf, 2, Node (Node (Leaf, 1, Leaf), 2, Leaf)), 0, Leaf), 4)
  , (Node (Leaf, 2, Node (Leaf, 0, Leaf)), 2)
  , (Node (Node (Leaf, 1, Node (Leaf, 0, Node (Leaf, 1, Leaf))), 0, Leaf), 4)
  , (Node (Node (Leaf, 1, Leaf), 3, Node (Leaf, 0, Leaf)), 3)
  , (Node (Leaf, 1, Node (Leaf, 1, Node (Leaf, 3, Node (Leaf, 1, Leaf)))), 4)
  , (Node (Node (Node (Leaf, 3, Leaf), 3, Leaf), 1, Node (Leaf, 0, Leaf)), 4)
  , (Node (Node (Leaf, 0, Leaf), 3, Node (Leaf, 3, Leaf)), 3)
  , (Node (Leaf, 1, Node (Node (Leaf, 3, Leaf), 1, Node (Leaf, 0, Leaf))), 4)
  , (Node (Leaf, 3, Node (Node (Leaf, 2, Node (Leaf, 2, Leaf)), 0, Leaf)), 4)
  ]
