specifyFunction2 treeMap
  [ (div2, Leaf, Leaf)
  , (div2, Node (Node (Leaf, 3, Node (Node (Leaf, 1, Leaf), 2, Leaf)), 0, Leaf), Node (Node (Leaf, 1, Node (Node (Leaf, 0, Leaf), 1, Leaf)), 0, Leaf))
  , (div2, Node (Node (Leaf, 1, Node (Leaf, 0, Leaf)), 1, Leaf), Node (Node (Leaf, 0, Node (Leaf, 0, Leaf)), 0, Leaf))
  , (div2, Node (Node (Node (Leaf, 0, Node (Leaf, 3, Leaf)), 3, Leaf), 1, Leaf), Node (Node (Node (Leaf, 0, Node (Leaf, 1, Leaf)), 1, Leaf), 0, Leaf))
  , (div2, Node (Leaf, 3, Node (Node (Leaf, 1, Leaf), 1, Leaf)), Node (Leaf, 1, Node (Node (Leaf, 0, Leaf), 0, Leaf)))
  , (div2, Node (Node (Node (Leaf, 0, Leaf), 0, Leaf), 1, Node (Leaf, 0, Leaf)), Node (Node (Node (Leaf, 0, Leaf), 0, Leaf), 0, Node (Leaf, 0, Leaf)))
  , (div2, Node (Node (Node (Node (Leaf, 2, Leaf), 3, Leaf), 1, Leaf), 1, Leaf), Node (Node (Node (Node (Leaf, 1, Leaf), 1, Leaf), 0, Leaf), 0, Leaf))
  , (div2, Node (Leaf, 0, Leaf), Node (Leaf, 0, Leaf))
  , (inc, Node (Node (Leaf, 1, Node (Node (Leaf, 2, Leaf), 3, Leaf)), 0, Leaf), Node (Node (Leaf, 2, Node (Node (Leaf, 3, Leaf), 4, Leaf)), 1, Leaf))
  , (div2, Node (Node (Leaf, 3, Leaf), 2, Node (Node (Leaf, 2, Leaf), 1, Leaf)), Node (Node (Leaf, 1, Leaf), 1, Node (Node (Leaf, 1, Leaf), 0, Leaf)))
  , (div2, Node (Leaf, 1, Node (Leaf, 2, Node (Node (Leaf, 1, Leaf), 2, Leaf))), Node (Leaf, 0, Node (Leaf, 1, Node (Node (Leaf, 0, Leaf), 1, Leaf))))
  , (inc, Node (Leaf, 1, Leaf), Node (Leaf, 2, Leaf))
  , (div2, Node (Leaf, 1, Node (Leaf, 0, Node (Node (Leaf, 2, Leaf), 0, Leaf))), Node (Leaf, 0, Node (Leaf, 0, Node (Node (Leaf, 1, Leaf), 0, Leaf))))
  , (div2, Node (Node (Leaf, 0, Leaf), 1, Node (Leaf, 0, Node (Leaf, 0, Leaf))), Node (Node (Leaf, 0, Leaf), 0, Node (Leaf, 0, Node (Leaf, 0, Leaf))))
  , (div2, Node (Node (Node (Leaf, 1, Leaf), 0, Leaf), 2, Leaf), Node (Node (Node (Leaf, 0, Leaf), 0, Leaf), 1, Leaf))
  , (div2, Node (Leaf, 3, Node (Node (Leaf, 1, Node (Leaf, 0, Leaf)), 0, Leaf)), Node (Leaf, 1, Node (Node (Leaf, 0, Node (Leaf, 0, Leaf)), 0, Leaf)))
  , (inc, Node (Node (Leaf, 3, Leaf), 0, Node (Node (Leaf, 0, Leaf), 2, Leaf)), Node (Node (Leaf, 4, Leaf), 1, Node (Node (Leaf, 1, Leaf), 3, Leaf)))
  , (inc, Node (Node (Leaf, 1, Node (Leaf, 0, Leaf)), 2, Leaf), Node (Node (Leaf, 2, Node (Leaf, 1, Leaf)), 3, Leaf))
  , (inc, Node (Leaf, 0, Node (Leaf, 1, Node (Node (Leaf, 1, Leaf), 1, Leaf))), Node (Leaf, 1, Node (Leaf, 2, Node (Node (Leaf, 2, Leaf), 2, Leaf))))
  , (div2, Node (Leaf, 3, Node (Node (Node (Leaf, 3, Leaf), 2, Leaf), 3, Leaf)), Node (Leaf, 1, Node (Node (Node (Leaf, 1, Leaf), 1, Leaf), 1, Leaf)))
  ]
