specifyFunction treeCollectLeaves
  [ (Leaf, [])
  , (Node (Leaf, F, Node (Node (Leaf, T, Node (Node (Leaf, F, Node (Leaf, T, Leaf)), T, Leaf)), F, Leaf)), [F, T, F, T, T, F])
  , (Node (Leaf, T, Node (Node (Leaf, T, Leaf), F, Leaf)), [T, T, F])
  , (Node (Leaf, F, Node (Leaf, T, Node (Leaf, T, Node (Leaf, T, Node (Leaf, T, Leaf))))), [F, T, T, T, T])
  , (Node (Node (Node (Node (Node (Leaf, F, Leaf), T, Leaf), T, Node (Leaf, F, Leaf)), F, Leaf), T, Leaf), [F, T, T, F, F, T])
  , (Node (Leaf, T, Node (Node (Node (Leaf, T, Node (Node (Leaf, T, Leaf), T, Leaf)), F, Leaf), T, Leaf)), [T, T, T, T, F, T])
  , (Node (Node (Node (Node (Leaf, T, Leaf), F, Leaf), T, Leaf), T, Leaf), [T, F, T, T])
  , (Node (Node (Leaf, T, Node (Leaf, F, Leaf)), T, Node (Node (Node (Leaf, T, Leaf), T, Leaf), T, Leaf)), [T, F, T, T, T, T])
  , (Node (Leaf, F, Node (Node (Leaf, F, Node (Node (Leaf, T, Leaf), T, Leaf)), F, Leaf)), [F, F, T, T, F])
  , (Node (Node (Leaf, F, Node (Node (Leaf, T, Leaf), T, Leaf)), T, Node (Leaf, T, Leaf)), [F, T, T, T, T])
  , (Node (Leaf, T, Node (Node (Leaf, F, Node (Node (Leaf, F, Leaf), T, Node (Leaf, F, Leaf))), T, Leaf)), [T, F, F, T, F, T])
  , (Node (Node (Node (Leaf, F, Leaf), T, Leaf), T, Node (Node (Leaf, F, Leaf), T, Leaf)), [F, T, T, F, T])
  , (Node (Node (Node (Leaf, T, Leaf), T, Leaf), F, Node (Node (Leaf, T, Leaf), F, Node (Leaf, T, Leaf))), [T, T, F, T, F, T])
  , (Node (Node (Leaf, F, Leaf), T, Node (Node (Node (Leaf, T, Node (Leaf, F, Leaf)), F, Leaf), T, Leaf)), [F, T, T, F, F, T])
  , (Node (Leaf, T, Node (Node (Leaf, T, Node (Leaf, T, Node (Leaf, T, Leaf))), T, Node (Leaf, F, Leaf))), [T, T, T, T, T, F])
  , (Node (Node (Node (Node (Node (Leaf, T, Leaf), F, Node (Leaf, F, Leaf)), F, Leaf), T, Leaf), T, Leaf), [T, F, F, F, T, T])
  , (Node (Leaf, F, Node (Leaf, F, Node (Leaf, T, Node (Leaf, T, Leaf)))), [F, F, T, T])
  , (Node (Leaf, T, Node (Leaf, F, Node (Node (Node (Leaf, F, Leaf), T, Leaf), F, Leaf))), [T, F, F, T, F])
  , (Node (Node (Leaf, T, Node (Leaf, T, Node (Leaf, T, Node (Leaf, F, Leaf)))), F, Leaf), [T, T, T, F, F])
  , (Node (Node (Leaf, F, Leaf), T, Node (Node (Leaf, F, Leaf), F, Leaf)), [F, T, F, F])
  ]
