specifyFunction2 treeNodesAtLevel
  [ (0, Leaf, 0)
  , (1, Node (Leaf, T, Node (Leaf, F, Node (Node (Leaf, T, Leaf), T, Leaf))), 1)
  , (1, Node (Node (Leaf, F, Node (Node (Leaf, T, Node (Node (Leaf, T, Leaf), T, Leaf)), F, Leaf)), F, Leaf), 1)
  , (0, Node (Leaf, F, Node (Node (Leaf, F, Leaf), T, Node (Leaf, F, Leaf))), 1)
  , (3, Node (Leaf, T, Node (Node (Node (Leaf, F, Node (Leaf, F, Leaf)), F, Node (Leaf, F, Leaf)), T, Leaf)), 2)
  , (1, Node (Leaf, F, Node (Node (Node (Leaf, F, Leaf), F, Node (Leaf, T, Leaf)), T, Node (Leaf, F, Leaf))), 1)
  , (2, Node (Leaf, T, Node (Node (Node (Leaf, F, Leaf), T, Node (Leaf, T, Leaf)), T, Node (Leaf, F, Leaf))), 2)
  , (2, Node (Leaf, T, Node (Node (Node (Leaf, F, Node (Node (Leaf, F, Leaf), F, Leaf)), F, Leaf), F, Leaf)), 1)
  , (2, Node (Leaf, F, Node (Node (Node (Node (Node (Leaf, F, Leaf), F, Leaf), T, Leaf), T, Leaf), T, Leaf)), 1)
  , (1, Node (Leaf, F, Node (Node (Leaf, F, Node (Node (Leaf, F, Leaf), F, Node (Leaf, F, Leaf))), T, Leaf)), 1)
  , (1, Node (Node (Leaf, F, Node (Node (Leaf, F, Node (Node (Leaf, T, Leaf), F, Leaf)), T, Leaf)), T, Leaf), 1)
  , (0, Node (Node (Node (Node (Leaf, F, Leaf), F, Leaf), F, Leaf), F, Node (Node (Leaf, F, Leaf), F, Leaf)), 1)
  , (2, Node (Leaf, F, Node (Node (Leaf, T, Node (Leaf, F, Node (Leaf, F, Leaf))), F, Leaf)), 1)
  , (0, Node (Leaf, T, Node (Leaf, F, Node (Leaf, T, Node (Node (Node (Leaf, T, Leaf), F, Leaf), T, Leaf)))), 1)
  , (0, Node (Node (Node (Node (Leaf, T, Leaf), F, Leaf), T, Leaf), T, Leaf), 1)
  , (2, Node (Node (Leaf, T, Node (Leaf, T, Node (Leaf, F, Node (Leaf, T, Leaf)))), T, Node (Leaf, F, Leaf)), 1)
  , (1, Node (Node (Leaf, F, Node (Node (Leaf, F, Node (Leaf, F, Leaf)), F, Node (Leaf, T, Leaf))), T, Leaf), 1)
  , (0, Node (Leaf, F, Node (Node (Node (Leaf, F, Leaf), F, Node (Leaf, T, Node (Leaf, T, Leaf))), F, Leaf)), 1)
  , (1, Node (Leaf, T, Node (Node (Node (Leaf, T, Leaf), T, Node (Leaf, F, Leaf)), T, Leaf)), 1)
  , (2, Node (Node (Leaf, T, Node (Leaf, T, Leaf)), F, Node (Node (Leaf, T, Node (Leaf, T, Leaf)), T, Leaf)), 2)
  ]
