specifyFunction concat
  [ (LNil, [])
  , (LCons ([1], LNil), [1])
  , (LCons ([0, 1], LNil), [0, 1])
  , (LCons ([3], LNil), [3])
  , (LCons ([], LCons ([3, 0], LCons ([], LNil))), [3, 0])
  , (LCons ([], LCons ([2, 0], LCons ([], LNil))), [2, 0])
  , (LCons ([3, 3], LCons ([2], LNil)), [3, 3, 2])
  , (LCons ([2, 2], LNil), [2, 2])
  , (LCons ([0, 3], LCons ([3, 3], LCons ([1, 1], LNil))), [0, 3, 3, 3, 1, 1])
  , (LCons ([], LNil), [])
  , (LCons ([0], LCons ([1], LNil)), [0, 1])
  , (LCons ([3], LCons ([], LCons ([3], LNil))), [3, 3])
  , (LCons ([2, 0], LCons ([0], LCons ([0], LCons ([2], LNil)))), [2, 0, 0, 0, 2])
  , (LCons ([], LCons ([], LCons ([3], LCons ([], LNil)))), [3])
  , (LCons ([], LCons ([1], LCons ([3, 3], LCons ([], LNil)))), [1, 3, 3])
  , (LCons ([], LCons ([0, 1], LNil)), [0, 1])
  , (LCons ([], LCons ([1], LNil)), [1])
  , (LCons ([], LCons ([1, 0], LCons ([3, 3], LCons ([], LNil)))), [1, 0, 3, 3])
  , (LCons ([1, 3], LCons ([1, 3], LNil)), [1, 3, 1, 3])
  , (LCons ([2, 0], LCons ([2], LCons ([], LCons ([3, 3], LNil)))), [2, 0, 2, 3, 3])
  ]
