specifyFunction2 (listRevTailcall <Nat>)
  [ -- ([]<Nat>, []<Nat>, []<Nat>)
  -- , ([]<Nat>, [0]<Nat>, [0]<Nat>)
  -- , ([]<Nat>, [1]<Nat>, [1]<Nat>)
  -- , ([]<Nat>, [1, 0]<Nat>, [1, 0]<Nat>)
  -- , ([0]<Nat>, []<Nat>, [0]<Nat>)
  -- , ([1]<Nat>, []<Nat>, [1]<Nat>)
  -- , ([1]<Nat>, [0]<Nat>, [1, 0]<Nat>)
    ([0, 1]<Nat>, []<Nat>, [1, 0]<Nat>)
  ]
