specifyFunction2 (listDrop <Nat>)
  [ -- ([]<Nat>, 0, []<Nat>)
    ([]<Nat>, 1, []<Nat>)
  -- , ([0]<Nat>, 0, [0]<Nat>)
  -- , ([0]<Nat>, 1, []<Nat>)
  -- , ([1]<Nat>, 0, [1]<Nat>)
  -- , ([1]<Nat>, 1, []<Nat>)
  -- , ([1, 0]<Nat>, 0, [1, 0]<Nat>)
  , ([1, 0]<Nat>, 1, [0]<Nat>)
  -- , ([0, 1]<Nat>, 0, [0, 1]<Nat>)
  -- , ([0, 1]<Nat>, 1, [1]<Nat>)
  -- , ([0, 1]<Nat>, 2, []<Nat>)
  ]
