specifyFunction2 (treeBInsert <Nat>)
  [ (Leaf<Nat> (), 0, Node<Nat> (Leaf<Nat> (), 0, Leaf<Nat> ()))
  , (Leaf<Nat> (), 1, Node<Nat> (Leaf<Nat> (), 1, Leaf<Nat> ()))
  , (Leaf<Nat> (), 2, Node<Nat> (Leaf<Nat> (), 2, Leaf<Nat> ()))
  , (Node<Nat> (Leaf<Nat> (), 1, Leaf<Nat> ()), 0, Node<Nat> (Node<Nat> (Leaf<Nat> (), 0, Leaf<Nat> ()), 1, Leaf<Nat> ()))
  , (Node<Nat> (Leaf<Nat> (), 1, Leaf<Nat> ()), 1, Node<Nat> (Leaf<Nat> (), 1, Leaf<Nat> ()))
  , (Node<Nat> (Leaf<Nat> (), 1, Leaf<Nat> ()), 2, Node<Nat> (Leaf<Nat> (), 1, Node<Nat> (Leaf<Nat> (), 2, Leaf<Nat> ())))
  , (Node<Nat> (Leaf<Nat> (), 0, Leaf<Nat> ()), 0, Node<Nat> (Leaf<Nat> (), 0, Leaf<Nat> ()))
  , (Node<Nat> (Leaf<Nat> (), 0, Leaf<Nat> ()), 1, Node<Nat> (Leaf<Nat> (), 0, Node<Nat> (Leaf<Nat> (), 1, Leaf<Nat> ())))
  , (Node<Nat> (Leaf<Nat> (), 0, Leaf<Nat> ()), 2, Node<Nat> (Leaf<Nat> (), 0, Node<Nat> (Leaf<Nat> (), 2, Leaf<Nat> ())))
  , (Node<Nat> (Leaf<Nat> (), 2, Leaf<Nat> ()), 0, Node<Nat> (Node<Nat> (Leaf<Nat> (), 0, Leaf<Nat> ()), 2, Leaf<Nat> ()))
  , (Node<Nat> (Leaf<Nat> (), 2, Leaf<Nat> ()), 1, Node<Nat> (Node<Nat> (Leaf<Nat> (), 1, Leaf<Nat> ()), 2, Leaf<Nat> ()))
  , (Node<Nat> (Leaf<Nat> (), 2, Leaf<Nat> ()), 2, Node<Nat> (Leaf<Nat> (), 2, Leaf<Nat> ()))
  , (Node<Nat> (Node<Nat> (Leaf<Nat> (), 0, Leaf<Nat> ()), 1, Leaf<Nat> ()), 0, Node<Nat> (Node<Nat> (Leaf<Nat> (), 0, Leaf<Nat> ()), 1, Leaf<Nat> ()))
  , (Node<Nat> (Node<Nat> (Leaf<Nat> (), 0, Leaf<Nat> ()), 1, Leaf<Nat> ()), 1, Node<Nat> (Node<Nat> (Leaf<Nat> (), 0, Leaf<Nat> ()), 1, Leaf<Nat> ()))
  , (Node<Nat> (Node<Nat> (Leaf<Nat> (), 0, Leaf<Nat> ()), 1, Leaf<Nat> ()), 2, Node<Nat> (Node<Nat> (Leaf<Nat> (), 0, Leaf<Nat> ()), 1, Node<Nat>(Leaf<Nat> (), 2, Leaf<Nat> ())))
  , (Node<Nat> (Leaf<Nat> (), 0, Node<Nat> (Leaf<Nat> (), 1, Leaf<Nat> ())), 2, Node<Nat> (Leaf<Nat> (), 0, Node<Nat> (Leaf<Nat> (), 1, Node<Nat>(Leaf<Nat> (), 2, Leaf<Nat> ()))))
  , (Node<Nat> (Node<Nat> (Leaf<Nat> (), 1, Leaf<Nat> ()), 2, Leaf<Nat> ()), 0, Node<Nat> (Node<Nat> (Node<Nat>(Leaf<Nat> (), 0, Leaf<Nat> ()), 1, Leaf<Nat> ()), 2, Leaf<Nat> ()))
  , (Node<Nat> (Leaf<Nat> (), 1, Node<Nat> (Leaf<Nat> (), 2, Leaf<Nat> ())), 0, Node<Nat> (Node<Nat> (Leaf<Nat> (), 0, Leaf<Nat> ()), 1, Node<Nat> (Leaf<Nat> (), 2, Leaf<Nat> ())))
  , (Node<Nat> (Leaf<Nat> (), 1, Node<Nat> (Leaf<Nat> (), 2, Leaf<Nat> ())), 1, Node<Nat> (Leaf<Nat> (), 1, Node<Nat> (Leaf<Nat> (), 2, Leaf<Nat> ())))
  , (Node<Nat> (Node<Nat> (Leaf<Nat> (), 1, Leaf<Nat> ()), 2, Leaf<Nat> ()), 0, Node<Nat> (Node<Nat> (Node<Nat>(Leaf<Nat> (), 0, Leaf<Nat> ()), 1, Leaf<Nat> ()), 2, Leaf<Nat> ()))
  ]
