specifyFunction (listTail <Nat>)
  [ ([]<Nat>, []<Nat>)
  , ([2]<Nat>, []<Nat>)
  , ([3]<Nat>, []<Nat>)
  , ([0, 3]<Nat>, [3]<Nat>)
  , ([3, 0, 3]<Nat>, [0, 3]<Nat>)
  , ([1]<Nat>, []<Nat>)
  , ([2, 3, 0]<Nat>, [3, 0]<Nat>)
  , ([0, 0, 3]<Nat>, [0, 3]<Nat>)
  , ([1, 3, 2]<Nat>, [3, 2]<Nat>)
  , ([2, 1]<Nat>, [1]<Nat>)
  ]
