specifyFunction2 (listFilter <Nat>)
  [ (isEven, []<Nat>, []<Nat>)
  , (isEven, [0, 2]<Nat>, [0, 2]<Nat>)
  , (isNonzero, []<Nat>, []<Nat>)
  , (isEven, [0, 1, 1]<Nat>, [0]<Nat>)
  , (isNonzero, [3, 0, 2]<Nat>, [3, 2]<Nat>)
  , (isEven, [2, 1, 3, 0]<Nat>, [2, 0]<Nat>)
  , (isNonzero, [0]<Nat>, []<Nat>)
  , (isNonzero, [2]<Nat>, [2]<Nat>)
  , (isNonzero, [1, 0, 1, 0]<Nat>, [1, 1]<Nat>)
  , (isEven, [0, 1, 2]<Nat>, [0, 2]<Nat>)
  , (isEven, [0, 3, 3]<Nat>, [0]<Nat>)
  , (isEven, [2, 0, 1]<Nat>, [2, 0]<Nat>)
  , (isNonzero, [1, 2]<Nat>, [1, 2]<Nat>)
  , (isEven, [2, 2, 3, 2]<Nat>, [2, 2, 2]<Nat>)
  , (isEven, [2]<Nat>, [2]<Nat>)
  , (isEven, [1, 1]<Nat>, []<Nat>)
  , (isNonzero, [0, 3, 1]<Nat>, [3, 1]<Nat>)
  , (isEven, [3, 0]<Nat>, [0]<Nat>)
  , (isEven, [0, 2, 0]<Nat>, [0, 2, 0]<Nat>)
  , (isNonzero, [1, 1, 0]<Nat>, [1, 1]<Nat>)
  ]
