specifyFunction (concat <Nat>)
  [ ([]<List Nat>, []<Nat>)
  , ([ []<Nat>, [0, 3]<Nat>, []<Nat>, [2, 1]<Nat> ]<List Nat>, [0, 3, 2, 1]<Nat>)
  , ([[]<Nat>, [2]<Nat>]<List Nat>, [2]<Nat>)
  , ([[2]<Nat>]<List Nat>, [2]<Nat>)
  , ([[]<Nat>]<List Nat>, []<Nat>)
  , ([[3]<Nat>]<List Nat>, [3]<Nat>)
  , ([[]<Nat>, [3]<Nat>]<List Nat>, [3]<Nat>)
  , ([[0]<Nat>, [2]<Nat>]<List Nat>, [0, 2]<Nat>)
  , ([[3, 0]<Nat>]<List Nat>, [3, 0]<Nat>)
  , ([[1]<Nat>]<List Nat>, [1]<Nat>)
  , ([[]<Nat>, [3, 3]<Nat>]<List Nat>, [3, 3]<Nat>)
  , ([ [2]<Nat>, [3]<Nat>, []<Nat>, [2, 0]<Nat> ]<List Nat>, [2, 3, 2, 0]<Nat>)
  , ([ [1]<Nat>, [3, 0]<Nat>, [3]<Nat>, [2]<Nat> ]<List Nat>, [1, 3, 0, 3, 2]<Nat>)
  , ([[]<Nat>, [1, 3]<Nat>]<List Nat>, [1, 3]<Nat>)
  , ([[2, 1]<Nat>, []<Nat>]<List Nat>, [2, 1]<Nat>)
  , ([ []<Nat>, [2]<Nat>, [0, 3]<Nat>, [2, 3]<Nat> ]<List Nat>, [2, 0, 3, 2, 3]<Nat>)
  , ([[2, 0]<Nat>]<List Nat>, [2, 0]<Nat>)
  , ([[]<Nat>, [3, 1]<Nat>, [2]<Nat>]<List Nat>, [3, 1, 2]<Nat>)
  , ([[3, 3]<Nat>, []<Nat>, [3]<Nat>]<List Nat>, [3, 3, 3]<Nat>)
  , ([[2, 0]<Nat>, []<Nat>, [1, 2]<Nat>]<List Nat>, [2, 0, 1, 2]<Nat>)
  ]
