specifyFunction (treeInOrder <Nat>)
  [ (Leaf<Nat>, []<Nat>)
  , (Node<Nat> (Node<Nat> (Leaf<Nat>, 0, Leaf<Nat>), 0, Node<Nat> (Leaf<Nat>, 2, Leaf<Nat>)), [0, 0, 2]<Nat>)
  , (Node<Nat> (Leaf<Nat>, 2, Node<Nat> (Leaf<Nat>, 3, Node<Nat> (Node<Nat> (Leaf<Nat>, 2, Leaf<Nat>), 1, Leaf<Nat>))), [2, 3, 2, 1]<Nat>)
  , (Node<Nat> (Node<Nat> (Node<Nat> (Node<Nat> (Leaf<Nat>, 3, Leaf<Nat>), 3, Leaf<Nat>), 1, Leaf<Nat>), 3, Leaf<Nat>), [3, 3, 1, 3]<Nat>)
  , (Node<Nat> (Leaf<Nat>, 0, Node<Nat> (Leaf<Nat>, 3, Leaf<Nat>)), [0, 3]<Nat>)
  , (Node<Nat> (Leaf<Nat>, 3, Leaf<Nat>), [3]<Nat>)
  , (Node<Nat> (Node<Nat> (Leaf<Nat>, 3, Node<Nat> (Leaf<Nat>, 2, Leaf<Nat>)), 0, Node<Nat> (Leaf<Nat>, 2, Leaf<Nat>)), [3, 2, 0, 2]<Nat>)
  , (Node<Nat> (Node<Nat> (Node<Nat> (Leaf<Nat>, 0, Leaf<Nat>), 2, Node<Nat> (Leaf<Nat>, 1, Leaf<Nat>)), 1, Leaf<Nat>), [0, 2, 1, 1]<Nat>)
  , (Node<Nat> (Node<Nat> (Node<Nat> (Leaf<Nat>, 3, Leaf<Nat>), 0, Leaf<Nat>), 0, Leaf<Nat>), [3, 0, 0]<Nat>)
  , (Node<Nat> (Leaf<Nat>, 0, Node<Nat> (Leaf<Nat>, 0, Node<Nat> (Node<Nat> (Leaf<Nat>, 2, Leaf<Nat>), 0, Leaf<Nat>))), [0, 0, 2, 0]<Nat>)
  , (Node<Nat> (Node<Nat> (Leaf<Nat>, 1, Leaf<Nat>), 0, Node<Nat> (Leaf<Nat>, 0, Leaf<Nat>)), [1, 0, 0]<Nat>)
  , (Node<Nat> (Node<Nat> (Leaf<Nat>, 2, Node<Nat> (Leaf<Nat>, 1, Node<Nat> (Leaf<Nat>, 3, Leaf<Nat>))), 3, Leaf<Nat>), [2, 1, 3, 3]<Nat>)
  , (Node<Nat> (Node<Nat> (Node<Nat> (Leaf<Nat>, 0, Leaf<Nat>), 3, Leaf<Nat>), 3, Leaf<Nat>), [0, 3, 3]<Nat>)
  , (Node<Nat> (Leaf<Nat>, 2, Node<Nat> (Leaf<Nat>, 2, Node<Nat> (Leaf<Nat>, 3, Node<Nat> (Leaf<Nat>, 2, Leaf<Nat>)))), [2, 2, 3, 2]<Nat>)
  , (Node<Nat> (Leaf<Nat>, 3, Node<Nat> (Leaf<Nat>, 2, Leaf<Nat>)), [3, 2]<Nat>)
  ]
