specifyFunction2 (treeNodesAtLevel <Boolean>)
  [ (Leaf<Boolean> (), 0, 0)
  , (Leaf<Boolean> (), 1, 0)
  , (Node<Boolean> (Leaf<Boolean> (), T (), Leaf<Boolean> ()), 0, 1)
  , (Node<Boolean> (Leaf<Boolean> (), T (), Leaf<Boolean> ()), 1, 0)
  , (Node<Boolean> (Node<Boolean> (Leaf<Boolean> (), T (), Leaf<Boolean> ()), T (), Leaf<Boolean> ()), 0, 1)
  , (Node<Boolean> (Node<Boolean> (Leaf<Boolean> (), T (), Leaf<Boolean> ()), T (), Leaf<Boolean> ()), 1, 1)
  , (Node<Boolean> (Node<Boolean> (Leaf<Boolean> (), T (), Leaf<Boolean> ()), T (), Node<Boolean> (Leaf<Boolean> (), T (), Leaf<Boolean> ())), 0, 1)
  , (Node<Boolean> (Node<Boolean> (Leaf<Boolean> (), T (), Leaf<Boolean> ()), T (), Node<Boolean> (Leaf<Boolean> (), T (), Leaf<Boolean> ())), 1, 2)
  , (Node<Boolean> (Node<Boolean> (Leaf<Boolean> (), T (), Leaf<Boolean> ()), T (), Node<Boolean> (Leaf<Boolean> (), T (), Leaf<Boolean> ())), 2, 0)
  , (Node<Boolean> (Node<Boolean> (Node<Boolean> (Leaf<Boolean> (), T (), Leaf<Boolean> ()), T (), Node<Boolean> (Leaf<Boolean> (), T (), Leaf<Boolean> ())), T (), Leaf<Boolean> ()), 0, 1)
  , (Node<Boolean> (Node<Boolean> (Node<Boolean> (Leaf<Boolean> (), T (), Leaf<Boolean> ()), T (), Node<Boolean> (Leaf<Boolean> (), T (), Leaf<Boolean> ())), T (), Leaf<Boolean> ()), 1, 1)
  ]
