specifyFunction (treeCountLeaves <Boolean>)
  [ (Leaf<Boolean>, 1)
  , (Node<Boolean> (Leaf<Boolean>, T, Node<Boolean> (Node<Boolean> (Leaf<Boolean>, F, Node<Boolean> (Leaf<Boolean>, F, Leaf<Boolean>)), T, Node<Boolean> (Leaf<Boolean>, F, Leaf<Boolean>))), 6)
  , (Node<Boolean> (Leaf<Boolean>, F, Node<Boolean> (Node<Boolean> (Leaf<Boolean>, T, Node<Boolean> (Leaf<Boolean>, F, Node<Boolean> (Leaf<Boolean>, F, Leaf<Boolean>))), T, Leaf<Boolean>)), 6)
  , (Node<Boolean> (Node<Boolean> (Node<Boolean> (Node<Boolean> (Node<Boolean> (Leaf<Boolean>, F, Node<Boolean> (Leaf<Boolean>, F, Leaf<Boolean>)), T, Leaf<Boolean>), T, Leaf<Boolean>), T, Leaf<Boolean>), T, Leaf<Boolean>), 7)
  , (Node<Boolean> (Leaf<Boolean>, T, Node<Boolean> (Node<Boolean> (Node<Boolean> (Node<Boolean> (Node<Boolean> (Leaf<Boolean>, F, Leaf<Boolean>), F, Leaf<Boolean>), F, Leaf<Boolean>), T, Leaf<Boolean>), F, Leaf<Boolean>)), 7)
  , (Node<Boolean> (Node<Boolean> (Node<Boolean> (Leaf<Boolean>, T, Node<Boolean> (Leaf<Boolean>, F, Leaf<Boolean>)), T, Node<Boolean> (Leaf<Boolean>, F, Leaf<Boolean>)), T, Node<Boolean> (Leaf<Boolean>, F, Leaf<Boolean>)), 7)
  , (Node<Boolean> (Node<Boolean> (Leaf<Boolean>, F, Node<Boolean> (Leaf<Boolean>, F, Node<Boolean> (Node<Boolean> (Leaf<Boolean>, T, Leaf<Boolean>), T, Node<Boolean> (Leaf<Boolean>, T, Leaf<Boolean>)))), F, Leaf<Boolean>), 7)
  , (Node<Boolean> (Node<Boolean> (Leaf<Boolean>, F, Leaf<Boolean>), F, Node<Boolean> (Node<Boolean> (Leaf<Boolean>, T, Leaf<Boolean>), F, Node<Boolean> (Node<Boolean> (Leaf<Boolean>, F, Leaf<Boolean>), F, Leaf<Boolean>))), 7)
  , (Node<Boolean> (Node<Boolean> (Leaf<Boolean>, T, Node<Boolean> (Leaf<Boolean>, T, Node<Boolean> (Node<Boolean> (Leaf<Boolean>, T, Leaf<Boolean>), T, Leaf<Boolean>))), T, Node<Boolean> (Leaf<Boolean>, T, Leaf<Boolean>)), 7)
  , (Node<Boolean> (Node<Boolean> (Leaf<Boolean>, T, Leaf<Boolean>), F, Node<Boolean> (Leaf<Boolean>, F, Node<Boolean> (Node<Boolean> (Leaf<Boolean>, T, Leaf<Boolean>), F, Node<Boolean> (Leaf<Boolean>, F, Leaf<Boolean>)))), 7)
  , (Node<Boolean> (Node<Boolean> (Leaf<Boolean>, T, Node<Boolean> (Leaf<Boolean>, T, Node<Boolean> (Leaf<Boolean>, F, Node<Boolean> (Leaf<Boolean>, T, Node<Boolean> (Leaf<Boolean>, F, Leaf<Boolean>))))), T, Leaf<Boolean>), 7)
  , (Node<Boolean> (Leaf<Boolean>, T, Node<Boolean> (Node<Boolean> (Node<Boolean> (Leaf<Boolean>, T, Node<Boolean> (Leaf<Boolean>, F, Leaf<Boolean>)), F, Leaf<Boolean>), T, Leaf<Boolean>)), 6)
  , (Node<Boolean> (Leaf<Boolean>, F, Node<Boolean> (Node<Boolean> (Leaf<Boolean>, F, Node<Boolean> (Leaf<Boolean>, T, Node<Boolean> (Node<Boolean> (Leaf<Boolean>, F, Leaf<Boolean>), F, Leaf<Boolean>))), F, Leaf<Boolean>)), 7)
  , (Node<Boolean> (Leaf<Boolean>, T, Node<Boolean> (Leaf<Boolean>, T, Node<Boolean> (Leaf<Boolean>, T, Node<Boolean> (Node<Boolean> (Node<Boolean> (Leaf<Boolean>, F, Leaf<Boolean>), F, Leaf<Boolean>), F, Leaf<Boolean>)))), 7)
  , (Node<Boolean> (Leaf<Boolean>, F, Node<Boolean> (Leaf<Boolean>, F, Node<Boolean> (Node<Boolean> (Leaf<Boolean>, T, Leaf<Boolean>), T, Node<Boolean> (Node<Boolean> (Leaf<Boolean>, T, Leaf<Boolean>), F, Leaf<Boolean>)))), 7)
  ]
